#!/bin/bash
echo updating the server and pihole
sleep 3
sudo apt-get update && sudo apt-get upgrade && sudo pihole -up
#
sleep 3
#
echo updating tor and its packages
#
sleep 3
#
sudo apt-get install tor && sudo apt-get install nyx
echo updating Docker and ContainerD
#
sleep 3
#
sudo apt install docker-ce docker-ce-cli containerd.io
echo turning off Nginx so we can update Certbot
sleep 3
sudo systemctl stop nginx
sudo certbot renew --dry-run
#
sleep 3
#
echo moving new certs to webmaster home/web/cert dir
#
sleep 3
#
sudo cp /etc/letsencrypt/live/[REDACTED]/privkey.pem /etc/letsencrypt/live/[REDACTED]/cert.pem /etc/letsencrypt/live/[REDACTED]/fullchain.pem /home/webmaster/web/certs
#
ls /home/webmaster/web/certs
sleep 5
#
echo Moving old certs to /oldcerts/ dir
sudo cp /home/webmaster/web/certs/fullchain.pem /home/webmaster/web/certs/cert.pem /home/webmaster/web/certs/privkey.pem /home/webmaster/web/certs/oldcerts
#
sleep 3
#
echo moving /home/webmaster/lighttpd.conf (seed) to /etc/lighttpd (main)
sudo cp /home/webmaster/lighttpd/lighttpd.conf /etc/lighttpd
#
#
sleep 10
#
echo Turning on nginx
sudo systemctl start nginx
echo Checking services are running
sudo systemctl status nginx && sleep 3 && sudo systemctl status tor && sleep 3 && sudo systemctl status docker
#
sleep 3
#
echo yarn version
yarn --version
#
sleep 3
#
#Cleaning up the server
sudo apt-get autoremove
#
sleep 3
#
#Getting server stats
neofetch
sleep 3
echo Whos connected?
w
echo Have a great day
