#!/usr/bin/bash
set -euo pipefail

NGINX_CONTAINER="nginx"
OUTPUT_FILE=""

usage() {
  echo "Usage: $(basename "$0") -o <output_file>"
  echo "  -o  Path to write the generated cloudflare-ips.conf"
  exit 1
}

while getopts "o:" opt; do
  case $opt in
    o) OUTPUT_FILE="$OPTARG" ;;
    *) usage ;;
  esac
done

[[ -z "$OUTPUT_FILE" ]] && { echo "ERROR: -o <output_file> is required."; usage; }

TEMP_FILE="$(mktemp)"

cleanup() { rm -f "$TEMP_FILE"; }
trap cleanup EXIT

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }

log "Fetching Cloudflare IP ranges..."

{
  echo "# Auto-generated by $(basename "$0") on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# Source: https://www.cloudflare.com/ips"
  echo "# Do not edit manually."
  echo ""

  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    log "Fetching $url"
    curl -fsSL --max-time 30 "$url" | while read -r cidr; do
      [[ -z "$cidr" ]] && continue
      echo "set_real_ip_from ${cidr};"
    done
  done

  echo "real_ip_header CF-Connecting-IP;"
} > "$TEMP_FILE"

COUNT=$(grep -c "set_real_ip_from" "$TEMP_FILE" || true)
if [[ "$COUNT" -lt 10 ]]; then
  log "ERROR: Only got $COUNT ranges, something looks wrong. Aborting."
  exit 1
fi

log "Got $COUNT IP ranges."

cp "$TEMP_FILE" "$OUTPUT_FILE"
log "Written to $OUTPUT_FILE"

log "Testing nginx config..."
if docker exec "$NGINX_CONTAINER" nginx -t 2>&1; then
  log "Config OK, reloading nginx..."
  docker exec "$NGINX_CONTAINER" nginx -s reload
  log "Done."
else
  log "ERROR: nginx config test failed. Not reloading."
  exit 1
fi
